# Generated by Django 5.2.15 on 2026-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_text", models.TextField()),
                ("jd_text", models.TextField()),
                ("score", models.IntegerField()),
                ("must_have_matched", models.JSONField(default=list)),
                ("must_have_missing", models.JSONField(default=list)),
                ("nice_to_have_matched", models.JSONField(default=list)),
                ("nice_to_have_missing", models.JSONField(default=list)),
                ("summary", models.TextField()),
                ("suggestions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
